# Generated by Django 4.1.3 on 2022-11-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('port', models.IntegerField()),
                ('ssh_user', models.CharField(max_length=255)),
                ('ssh_password', models.CharField(max_length=255)),
                ('rcon_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(default='', max_length=40)),
                ('flag', models.CharField(default='', max_length=4)),
                ('logo', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_version', models.CharField(default='unknown', max_length=32)),
                ('forfeit', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_maps', models.IntegerField()),
                ('title', models.CharField(default='', max_length=60)),
                ('skip_veto', models.BooleanField()),
                ('api_key', models.CharField(max_length=32)),
                ('veto_mappool', models.CharField(max_length=500)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('game_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameserver')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_set_as_team1', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_set_as_team2', to='core.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_set_as_team_winner', to='core.team')),
            ],
        ),
    ]
