# Generated by Django 4.1.3 on 2022-11-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
