# Generated by Django 4.1.3 on 2022-11-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gameserver_ssh_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='player_password',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
    ]
