# Generated by Django 4.1.3 on 2022-11-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gameserver_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='player_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='rcon_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
