# Generated by Django 4.1.3 on 2022-12-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_series_type_team_player1_team_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
