# Generated by Django 4.1.3 on 2022-12-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gameserver'),
        ),
    ]
