# Generated by Django 4.1.3 on 2022-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_match_game_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
