# Generated by Django 4.1.3 on 2022-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clinch_series',
            field=models.BooleanField(default=True, help_text="Don't play third match in BO3 if one team has already won 2."),
        ),
        migrations.AddField(
            model_name='match',
            name='maplist',
            field=models.CharField(default='de_dust2,de_inferno,de_mirage,de_nuke,de_overpass,de_train,de_vertigo', help_text='comma separated map list. (de_dust2,de_inferno)', max_length=1024),
        ),
        migrations.AddField(
            model_name='match',
            name='match_title',
            field=models.CharField(blank=True, default=None, help_text='La denne være blank så fikser Get5 Tittel selv.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='num_maps',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='match',
            name='players_per_team',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='match',
            name='skip_veto',
            field=models.BooleanField(default=False),
        ),
    ]
