# Generated by Django 4.1.3 on 2022-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(default='NO', max_length=4),
        ),
    ]
