# Generated by Django 4.1.3 on 2022-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_player_esportal_username_alter_player_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='maplist',
            field=models.TextField(default='*** Competitive ***\nde_inferno\nde_overpass\nde_train\nde_vertigo\nde_ancient\nde_anubis\nde_breach\nde_cache\nde_dust2\nde_mirage\nde_tuscan\nde_nuke\n\n*** Wingman ***\nde_inferno\nde_overpass\nde_train\nde_vertigo\nde_blagai\nde_cbble\nde_lake\nde_prime\nde_shortdust\nde_shortnuk\n\n*** Wingman Workshop ***\nde_marine\nde_gracia\nde_evon\nde_eternity\nde_akihabara\nde_austria\nde_beerhouse\n', help_text='new line separated map list. (de_dust2,de_inferno)', max_length=1024),
        ),
    ]
