# Generated by Django 4.1.3 on 2022-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_match_maplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='internal_url',
            field=models.CharField(blank=True, help_text='If you are hosting this web-app', max_length=255, null=True),
        ),
    ]
