# Generated by Django 4.1.3 on 2022-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gameserver_internal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date_time',
            field=models.DateTimeField(blank=True, help_text='When is the match planned for?', null=True),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='internal_url',
            field=models.CharField(blank=True, help_text='If you are hosting this app on the same local network as the game-server.', max_length=255, null=True),
        ),
    ]
