# Generated by Django 4.1.4 on 2022-12-11 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_match_match_date_time_alter_gameserver_internal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='Is Public',
            field=models.BooleanField(default=True, verbose_name='Is the server public?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='admins',
            field=models.ManyToManyField(related_name='admined_gameservers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameserver',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_gameservers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='maplist',
            field=models.TextField(default='*** Competitive ***\nde_inferno\nde_overpass\nde_train\nde_vertigo\nde_ancient\nde_anubis\nde_breach\nde_cache\nde_dust2\nde_mirage\nde_tuscan\nde_nuke\n\n*** Wingman ***\nde_inferno\nde_overpass\nde_train\nde_vertigo\nde_blagai\nde_cbble\nde_lake\nde_prime\nde_shortdust\nde_shortnuk\n\n*** Wingman Workshop ***\nde_marine\nde_gracia\nde_evon\nde_eternity\nde_akihabara\nde_austria\nde_beerhouse\n\n*** Vintercup ***\nde_inferno\nde_overpass\nde_train\nde_vertigo\nde_cbble\nde_lake\nde_shortdust\n', help_text='7 Maps. One map per line.', max_length=1024),
        ),
    ]
