from .player import playerDeleteTestCase
from .player import playerUpdateTestCase
from .player import playerDetailTestCase
from .player import playerCreateTestCase
from .player import playerListTestCase
from .match import MatchDeleteTestCase
from .match import MatchUpdateTestCase
from .match import MatchDetailTestCase
from .match import MatchCreateTestCase
from .match import MatchListTestCase
from .team import TeamDeleteTestCase
from .team import TeamUpdateTestCase
from .team import TeamDetailTestCase
from .team import TeamCreateTestCase
from .team import TeamListTestCase
from .game_server import GameServerDeleteTestCase
from .game_server import GameServerUpdateTestCase
from .game_server import GameServerDetailTestCase
from .game_server import GameServerCreateTestCase
from .game_server import GameServerListTestCase
