from .match import MatchDeleteView
from .match import MatchUpdateView
from .match import MatchDetailView
from .match import MatchCreateView
from .match import MatchListView
from .team import TeamDeleteView
from .team import TeamUpdateView
from .team import TeamDetailView
from .team import TeamCreateView
from .team import TeamListView
from .game_server import *
