from .game_server_delete import GameServerDeleteView
from .game_server_update import GameServerUpdateView
from .game_server_detail import GameServerDetailView
from .game_server_create import GameServerCreateView
from .game_server_list import GameServerListView
